### ISSUE TITLE
Fix: Tailwind css import on jsx component

### ISSUE THREAD

**Issue by akash5100** [sahil-m416/next-js#1]
here: https://github.com/sahil-m416/next-js/blob/main/tailwind.config.js#L3

Line 3 and 4
Replace `" jsx"` with `"jsx"`

Solution would be:
```js
    content: ["./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",],
```

**Comment by sahil-m416** [comment]
Thanks @akash5100 this worked !!!1
